name: pdf_test
description: "PDF Scanner test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_doc_scanner: ^0.0.16
  flutter_pdfview: ^1.4.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.4
  injectable: ^2.5.0
  intl: ^0.20.2
  image: ^4.5.4
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path: ^1.9.1
  pdf_render: ^1.4.12
  pdf_thumbnail: ^0.1.6+1
  pro_image_editor: ^9.13.0
  share_plus: ^11.0.0
  syncfusion_flutter_pdf: ^30.1.37

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  objectbox_generator: ^4.3.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/sf_pro_reg.otf

flutter_gen:
  output: lib/ui_assets
  integrations:
    flutter_svg: true

